### ISSUE TITLE
HD Camera  bug

### ISSUE THREAD

**Issue by MR-ZiWeiter** [jlempen/MateBook-X-Pro-2020-OpenCore#1]
camera not working

**Comment by jlempen** [comment]
The camera's been working fine on my machine. Of course the "nose-cam" key needs to be retracted for it to produce a picture instead of a black picture ;-)

Does the camera show up in the `camera` section of your macOS `system report`? It should also show up in the `USB` section as well.

As the camera is a simple USB 2.0 device on the MateBook X Pro 2020, there's no reason it wouldn't work, provided the USB mapping is correct. I would suggest you to build a new `USBMap.kext` for your specific device using the [USBToolBox](https://github.com/USBToolBox/tool) tool in Windows or Linux and replace the one bundled in my EFI folder. It is possible that some versions of the MBXP 2020 need a USB map different from mine.

**Comment by MR-ZiWeiter** [comment]
Thanks, I'll try it. I see that the device information is normally mounted on the camera

**Comment by jlempen** [comment]
Closed due to no feedback
